find -name "*.h5.feioutput" -delete
find -name "*.h5.*.feioutput" -delete
find -name "essi_*.log" -delete
find -name "new.log" -delete
find -name "terminal.log" -delete
find -name "measure_damping.m" -delete
find -name "RealESSI_VERSION_INFO.txt" -delete
find -name "MSESSI_VERSION_INFO.txt" -delete
find -name "*.pyc" -delete